//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InAppPurchasesApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gun()
        {
            this.Levels = new HashSet<Level>();
        }
    
        public int GunId { get; set; }
        public string Name { get; set; }
        public string NameStatic { get; set; }
        public int Type { get; set; }
        public double Pause { get; set; }
        public int GunLevel { get; set; }
        public int BoostCost { get; set; }
        public bool Unlocked { get; set; }
        public string Description { get; set; }
        public string PathToPrefab { get; set; }
        public string PathToIcon { get; set; }
        public string PathToAchivementIcon { get; set; }
        public string PathToAchivementIconLocked { get; set; }
        public string PathToWeaponAudio { get; set; }
        public bool TwoHanded { get; set; }

        public Helpers.GunType GunType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Level> Levels { get; set; }
    }
}
