//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InAppPurchasesApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        public int LevelId { get; set; }
        public int GunId { get; set; }
        public int GunLevel { get; set; }
        public int Cost { get; set; }
        public int Damage { get; set; }
        public int BulletsInClip { get; set; }
        public int BulletsMax { get; set; }
    
        public virtual Gun Gun { get; set; }
    }
}
