//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InAppPurchasesApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWeapon
    {
        public int UserWeaponId { get; set; }
        public int UserId { get; set; }
        public int GameId { get; set; }
        public int WeaponId { get; set; }
        public int GunLevel { get; set; }
        public int Experience { get; set; }
        public bool BoostActive { get; set; }
        public bool Unlocked { get; set; }
        public string BoostEndTime { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
